Add terms and conditions accept to client
CurrencyCloud/currencycloud-java pull request #186
Opened 2024-12-02 11:58 UTC by Ashley-Peck

2024-12-02 12:40 UTC, ccdredzik approved these changes

2024-12-02 16:35 UTC, jonathancouchman requested changes

2024-12-02 16:35 UTC, jonathancouchman commented on src/main/java/com/currencycloud/client/model/TermsAndConditionsAcceptance.java
> +  private UUID acceptanceId;
For consistency with other entities the Id should be a String rather than a UUID

2024-12-03 09:22 UTC, jonathancouchman approved these changes

2024-12-03 15:55 UTC, merged